default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: 'development__slack-photos'
  host: 127.0.0.1
  username: root
  password:

test:
  <<: *default
  database: 'test__slack-photos'
  host: 127.0.0.1
  username: root
  password:

production:
  <<: *default
  database: 'test-slack-photos'
  host: 127.0.0.1
  username: root
  password:
